# Generated by Django 5.2.5 on 2025-09-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_add_new_project_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="ipbss_remedy",
            field=models.CharField(
                blank=True, help_text="IPBSS Remedy identifier", max_length=100
            ),
        ),
    ]
