# Generated by Django 5.2.5 on 2025-09-18 05:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HolidayCalendar",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("date", models.DateField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "is_recurring",
                    models.BooleanField(default=False, help_text="Recurring annually"),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Leave code like AL, SL, AL.5",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name like 'Annual Leave'", max_length=100
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "is_paid",
                    models.BooleanField(
                        default=True, help_text="Whether this leave type is paid"
                    ),
                ),
                (
                    "affects_entitlement",
                    models.BooleanField(
                        default=True, help_text="Counts against annual entitlement"
                    ),
                ),
                (
                    "is_half_day",
                    models.BooleanField(
                        default=False, help_text="Half-day leave type (.5 codes)"
                    ),
                ),
                (
                    "color_code",
                    models.CharField(
                        default="#007bff",
                        help_text="Color for calendar display",
                        max_length=7,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("requires_approval", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "duration_days",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Duration in days (0.5 for half days)",
                        max_digits=4,
                    ),
                ),
                ("reason", models.TextField(help_text="Reason for leave")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_leave_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_leave_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="leaves.leavetype",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="LeaveComment",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("comment", models.TextField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "leave_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="leaves.leaverequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeaveStatusHistory",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "previous_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=10,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "leave_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="leaves.leaverequest",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Leave status histories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeaveBalance",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year", models.PositiveIntegerField(default=2025)),
                (
                    "allocated_days",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
                ),
                (
                    "used_days",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
                ),
                (
                    "pending_days",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_balances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="leaves.leavetype",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "employee__first_name", "leave_type__code"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeEntitlement",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year", models.PositiveIntegerField(default=2025)),
                (
                    "annual_holiday_entitlement",
                    models.DecimalField(
                        decimal_places=1,
                        default=25.0,
                        help_text="Annual holiday entitlement in days",
                        max_digits=5,
                    ),
                ),
                (
                    "days_carried_over",
                    models.DecimalField(
                        decimal_places=1,
                        default=0.0,
                        help_text="Days carried over from previous year",
                        max_digits=5,
                    ),
                ),
                (
                    "time_in_lieu",
                    models.DecimalField(
                        decimal_places=1,
                        default=0.0,
                        help_text="Time in Lieu (TIL) days available",
                        max_digits=5,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="leaves.department",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entitlements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "employee__first_name"],
                "unique_together": {("employee", "year")},
            },
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["employee", "status"], name="leaves_leav_employe_7236fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["start_date", "end_date"], name="leaves_leav_start_d_96457d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["status", "start_date"], name="leaves_leav_status_bca0ae_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="leavebalance",
            unique_together={("employee", "leave_type", "year")},
        ),
    ]
